### ISSUE TITLE
Can this program modify record files to add obstacles (point cloud data)?

### ISSUE THREAD

**Issue by luogyu7** [ntutangyun/CyberRecordParser#1]
Hi, I have a question About this program , may I ask your advice?
Apollo data sharing platform: https://apollo.auto/southbay_cn.html download data set, include: gt_pose_data, image_data, imu_data, params, pcd_data, split. 

Can I use the program and the dataset to generate my own record file ?
And can I use the program to add obstacles data to record file ?

**Comment by ntutangyun** [comment]
> Can I use the program and the dataset to generate my own record file?

Hi, the script only parses the record file, and currently, it cannot be used to generate the record file. 
But from the source, you can definitely check out how the binary structure of the record file and create your own generator.

> Can I use the program and the dataset to generate my own record file?
yes you could write your own creator and add obstacles to the binary recording file, if you fully understand the file structure. 

BTW, if you're doing research, I'm also a Ph.D. student and open to collaboration. I can help you write the script you want. won't take long :)

**Comment by luogyu7** [comment]
Yes ，I need it, and many thanks for your reply.

About collaboration. Happy to cooperate   

In a nutshell, my research is Apollo platform perception detection method research ,so a need a help at record file with obstacle adding  to test the apollo perception detection .  I have no valuable method yet.

I need a program that can realize adding 3D obstacle data  to record file.  I need some suggestions.

If it's convenient ,for the sake of argument, I will email you to discuss more details soon.

**Comment by ntutangyun** [comment]
sure. we can discuss this through email. kindlly send details to yun005 [at] e.ntu.edu.sg. :)

**Comment by luogyu7** [comment]
ok，I will email you soon.

**Comment by luogyu7** [comment]
Hi , I just sent you the email from luogyuxx@ruc.edu.cn , please check it. 
Thanks.
